export const ROWS = [
  {
    label: "Air Fare",
    std: "Tickets",
    psk: "airFarePSup",
    pak: "airFareP",
    sk: "airFareSup",
    ak: "airFare",
    dash: false,
  },
  {
    label: "Rail Fare",
    std: "Tickets",
    psk: "railFarePSup",
    pak: "railFareP",
    sk: "railFareSup",
    ak: "railFare",
    dash: false,
  },
  {
    label: "Lodging",
    std: "Bill / Receipt",
    psk: "lodgingPSup",
    pak: "lodgingP",
    sk: "lodgingSup",
    ak: "lodging",
    dash: false,
  },
  {
    label: "Boarding (Hotel)",
    std: "Bill / Receipt",
    psk: null,
    pak: null,
    sk: "boardingHSup",
    ak: "boardingH",
    dash: true,
  },
  {
    label: "Boarding (Others)",
    std: "Bill / Receipt",
    psk: "boardingOPSup",
    pak: "boardingOP",
    sk: "boardingOSup",
    ak: "boardingO",
    dash: false,
  },
  {
    label: "Daily Allowance",
    std: "Breakfast, Lunch,\nDinner",
    psk: "dailyPSup",
    pak: "dailyP",
    sk: "dailySup",
    ak: "dailyAmt",
    dash: false,
  },
  {
    label: "Incidentals",
    std: "",
    psk: "incPSup",
    pak: "incP",
    sk: "incSup",
    ak: "incidentals",
    dash: false,
  },
  {
    label: "Conveyance (Local)",
    std: "Movement Details",
    psk: "convPSup",
    pak: "convP",
    sk: "convSup",
    ak: "conveyance",
    dash: false,
  },
  {
    label: "Car Hire",
    std: "Bill / Receipt",
    psk: "carPSup",
    pak: "carP",
    sk: "carSup",
    ak: "carHire",
    dash: false,
  },
  {
    label: "Telephone",
    std: "Bill / Receipt",
    psk: "telPSup",
    pak: "telP",
    sk: "telSup",
    ak: "telephone",
    dash: false,
  },
  {
    label: "Bus Entertainment",
    std: "Cash Memos",
    psk: "busPSup",
    pak: "busP",
    sk: "busSup",
    ak: "busEnt",
    dash: false,
  },
  {
    label: "Others (Annexure)",
    std: "Cash Memos",
    psk: "othPSup",
    pak: "othP",
    sk: "othSup",
    ak: "others",
    dash: false,
  },
];
