export const FONT_FAMILIES = [
  {
    id: "mono",
    label: "Mono (Default)",
    css: "ui-monospace, 'Courier New', monospace",
    google: null,
  },
  {
    id: "courier",
    label: "Courier New",
    css: "'Courier New', Courier, monospace",
    google: null,
  },
  {
    id: "consolas",
    label: "Consolas",
    css: "Consolas, 'Lucida Console', monospace",
    google: null,
  },
  {
    id: "arial",
    label: "Arial",
    css: "Arial, Helvetica, sans-serif",
    google: null,
  },
  {
    id: "verdana",
    label: "Verdana",
    css: "Verdana, Geneva, sans-serif",
    google: null,
  },
  {
    id: "tahoma",
    label: "Tahoma",
    css: "Tahoma, Geneva, sans-serif",
    google: null,
  },
  {
    id: "trebuchet",
    label: "Trebuchet MS",
    css: "'Trebuchet MS', sans-serif",
    google: null,
  },
  {
    id: "calibri",
    label: "Calibri",
    css: "Calibri, 'Segoe UI', sans-serif",
    google: null,
  },
  {
    id: "georgia",
    label: "Georgia",
    css: "Georgia, 'Times New Roman', serif",
    google: null,
  },
  {
    id: "times",
    label: "Times New Roman",
    css: "'Times New Roman', Times, serif",
    google: null,
  },
  {
    id: "garamond",
    label: "Garamond",
    css: "Garamond, 'Times New Roman', serif",
    google: null,
  },
  {
    id: "palatino",
    label: "Palatino",
    css: "'Palatino Linotype', 'Book Antiqua', Palatino, serif",
    google: null,
  },
  {
    id: "impact",
    label: "Impact",
    css: "Impact, 'Arial Narrow', sans-serif",
    google: null,
  },
  {
    id: "condensed",
    label: "Arial Narrow",
    css: "'Arial Narrow', sans-serif",
    google: null,
  },
  {
    id: "roboto",
    label: "Roboto",
    css: "'Roboto', sans-serif",
    google: "Roboto:wght@400;700",
  },
  {
    id: "opensans",
    label: "Open Sans",
    css: "'Open Sans', sans-serif",
    google: "Open+Sans:wght@400;700",
  },
  {
    id: "lato",
    label: "Lato",
    css: "'Lato', sans-serif",
    google: "Lato:wght@400;700",
  },
  {
    id: "montserrat",
    label: "Montserrat",
    css: "'Montserrat', sans-serif",
    google: "Montserrat:wght@400;700",
  },
  {
    id: "poppins",
    label: "Poppins",
    css: "'Poppins', sans-serif",
    google: "Poppins:wght@400;700",
  },
  {
    id: "nunito",
    label: "Nunito",
    css: "'Nunito', sans-serif",
    google: "Nunito:wght@400;700",
  },
  {
    id: "raleway",
    label: "Raleway",
    css: "'Raleway', sans-serif",
    google: "Raleway:wght@400;700",
  },
  {
    id: "inter",
    label: "Inter",
    css: "'Inter', sans-serif",
    google: "Inter:wght@400;700",
  },
  {
    id: "worksans",
    label: "Work Sans",
    css: "'Work Sans', sans-serif",
    google: "Work+Sans:wght@400;700",
  },
  {
    id: "rubik",
    label: "Rubik",
    css: "'Rubik', sans-serif",
    google: "Rubik:wght@400;700",
  },
  {
    id: "ptsans",
    label: "PT Sans",
    css: "'PT Sans', sans-serif",
    google: "PT+Sans:wght@400;700",
  },
  {
    id: "mukta",
    label: "Mukta",
    css: "'Mukta', sans-serif",
    google: "Mukta:wght@400;700",
  },
  {
    id: "karla",
    label: "Karla",
    css: "'Karla', sans-serif",
    google: "Karla:wght@400;700",
  },
  {
    id: "quicksand",
    label: "Quicksand",
    css: "'Quicksand', sans-serif",
    google: "Quicksand:wght@400;700",
  },
  {
    id: "barlow",
    label: "Barlow",
    css: "'Barlow', sans-serif",
    google: "Barlow:wght@400;700",
  },
  {
    id: "manrope",
    label: "Manrope",
    css: "'Manrope', sans-serif",
    google: "Manrope:wght@400;700",
  },
  {
    id: "heebo",
    label: "Heebo",
    css: "'Heebo', sans-serif",
    google: "Heebo:wght@400;700",
  },
  {
    id: "dmsans",
    label: "DM Sans",
    css: "'DM Sans', sans-serif",
    google: "DM+Sans:wght@400;700",
  },
  {
    id: "outfit",
    label: "Outfit",
    css: "'Outfit', sans-serif",
    google: "Outfit:wght@400;700",
  },
  {
    id: "jost",
    label: "Jost",
    css: "'Jost', sans-serif",
    google: "Jost:wght@400;700",
  },
  {
    id: "merriweather",
    label: "Merriweather",
    css: "'Merriweather', serif",
    google: "Merriweather:wght@400;700",
  },
  {
    id: "playfair",
    label: "Playfair Display",
    css: "'Playfair Display', serif",
    google: "Playfair+Display:wght@400;700",
  },
  {
    id: "lora",
    label: "Lora",
    css: "'Lora', serif",
    google: "Lora:wght@400;700",
  },
  {
    id: "ptserif",
    label: "PT Serif",
    css: "'PT Serif', serif",
    google: "PT+Serif:wght@400;700",
  },
  {
    id: "ptbody",
    label: "Crimson Text",
    css: "'Crimson Text', serif",
    google: "Crimson+Text:wght@400;700",
  },
  {
    id: "ebgaramond",
    label: "EB Garamond",
    css: "'EB Garamond', serif",
    google: "EB+Garamond:wght@400;700",
  },
  {
    id: "domine",
    label: "Domine",
    css: "'Domine', serif",
    google: "Domine:wght@400;700",
  },
  {
    id: "bitter",
    label: "Bitter",
    css: "'Bitter', serif",
    google: "Bitter:wght@400;700",
  },
  {
    id: "cormorant",
    label: "Cormorant",
    css: "'Cormorant', serif",
    google: "Cormorant:wght@400;700",
  },
  {
    id: "spectral",
    label: "Spectral",
    css: "'Spectral', serif",
    google: "Spectral:wght@400;700",
  },
  {
    id: "robotomono",
    label: "Roboto Mono",
    css: "'Roboto Mono', monospace",
    google: "Roboto+Mono:wght@400;700",
  },
  {
    id: "sourcecodepro",
    label: "Source Code Pro",
    css: "'Source Code Pro', monospace",
    google: "Source+Code+Pro:wght@400;700",
  },
  {
    id: "jetbrainsmono",
    label: "JetBrains Mono",
    css: "'JetBrains Mono', monospace",
    google: "JetBrains+Mono:wght@400;700",
  },
  {
    id: "ibmplexmono",
    label: "IBM Plex Mono",
    css: "'IBM Plex Mono', monospace",
    google: "IBM+Plex+Mono:wght@400;700",
  },
  {
    id: "spacemono",
    label: "Space Mono",
    css: "'Space Mono', monospace",
    google: "Space+Mono:wght@400;700",
  },
  {
    id: "inconsolata",
    label: "Inconsolata",
    css: "'Inconsolata', monospace",
    google: "Inconsolata:wght@400;700",
  },
  {
    id: "oswald",
    label: "Oswald (Condensed)",
    css: "'Oswald', sans-serif",
    google: "Oswald:wght@400;700",
  },
  {
    id: "bebasneue",
    label: "Bebas Neue (Display)",
    css: "'Bebas Neue', sans-serif",
    google: "Bebas+Neue",
  },
  {
    id: "anton",
    label: "Anton (Bold Display)",
    css: "'Anton', sans-serif",
    google: "Anton",
  },
  {
    id: "archivoblack",
    label: "Archivo Black",
    css: "'Archivo Black', sans-serif",
    google: "Archivo+Black",
  },
  {
    id: "abril",
    label: "Abril Fatface",
    css: "'Abril Fatface', serif",
    google: "Abril+Fatface",
  },
  {
    id: "pacifico",
    label: "Pacifico (Script)",
    css: "'Pacifico', cursive",
    google: "Pacifico",
  },
  {
    id: "caveat",
    label: "Caveat (Handwritten)",
    css: "'Caveat', cursive",
    google: "Caveat:wght@400;700",
  },
  {
    id: "dancingscript",
    label: "Dancing Script",
    css: "'Dancing Script', cursive",
    google: "Dancing+Script:wght@400;700",
  },
  {
    id: "shadowsinto",
    label: "Shadows Into Light",
    css: "'Shadows Into Light', cursive",
    google: "Shadows+Into+Light",
  },
  {
    id: "permanentmarker",
    label: "Permanent Marker",
    css: "'Permanent Marker', cursive",
    google: "Permanent+Marker",
  },
];

export const GOOGLE_FONTS_URL = `https://fonts.googleapis.com/css2?${FONT_FAMILIES.filter(
  (f) => f.google,
)
  .map((f) => `family=${f.google}`)
  .join("&")}&display=swap`;
